server:
  port: 8082

spring:
  application:
    name: keynote-service
  datasource:
    url: jdbc:h2:mem:testdb2
    username: sa
    password: 
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

